### PR TITLE
Update mba bridge to latest verification

### PR DESCRIPTION
**Pull request by shawntanzk**
creating a PR for ease

### CODE REVIEW

**Comment by patrick-lloyd-ray** [comment]
@shawntanzk Would you like me to review the "curated" terms then change them to "verified?" I think we may have looked at a lot of them already (but maybe that was some other spreadsheet of neuroanatomy terms and I'm confused).

**Comment by shawntanzk** [comment]
@patrick-lloyd-ray - yes :) 
Basically what we have done is programmatically go through the curated sheet before and for all terms that were marked "ok" we added a verified in the mapping. The rest I then went through and curated what I thought was right. Some of them might be previous ok, but because I changed the mapping (eg to a more specific curation with the more expressive system we have now) in which case, I changed it to curated. 
Please do let me know if there's any other questions or if there's anyway I can help :) thanks heaps!

**Comment by shawntanzk** [comment]
@patrick-lloyd-ray just following up on this, wondering how its going. No worries if it needs more time, just asking to see what plans we can make with this (e.g. we can use what we have first and all and reiterate as we go along). Thanks

**Comment by patrick-lloyd-ray** [comment]
@shawntanzk, it's in progress, but should be done soon, say within a week. SfN prep has been taking a lot of my time recently.

**Comment by shawntanzk** [comment]
Thanks heaps @patrick-lloyd-ray really appreciate it :)

**Pull request merged**
