### PR TITLE
Verified curated classes.

### PR DESCRIPTION
**Pull request by patrick-lloyd-ray**
@shawntanzk -- I don't have write permission to that repo, so I pushed the commit here. There are two that we should agree on and one I changed that I would like to verify with you. I'll add comments for the outstanding issues. 

Related to: https://github.com/obophenotype/ABA_Uberon/pull/31

### CODE REVIEW

**Comment by patrick-lloyd-ray** [comment]
Screen Shot 2022-11-22 at 4 00 46 PM

anterior cingulate area ^ is separated in MBA into dorsal and ventral parts, but UBERON does not seem to have this granularity. So, I'm not sure that MBA:296 (anterior cingulate area, ventral part, layer 2/3) should be modeled as equivalent UBERON:8440000 + UBERON:0035013 (which would be anterior cingulate area layer 2/3 without the ventral distinction, correct?).

The other one I did not verify is MBA:298 (magnocellular nucleus). I think it was in the sheet as subclass part of UBERON:0010010 (basal nucleus of telencephalon). I think in the mouse (according to MBA), the magnocellular nucleus is the most ventral part of the ventral region of the palladium (and is disjoint with the substantia innominata). The ventral region of the palladium is highlighted in the following image, with the outlines those of the magnocellular nucleus and substantia innominata). 
Screen Shot 2022-11-22 at 4 13 52 PM
I'm fairly sure human is altogether different, though, so I'm not sure how you want to handle it.

**Comment by shawntanzk** [comment]
> Good catch, will weaken it to subclass and that should work

actually will make it simple subclass of http://purl.obolibrary.org/obo/UBERON_0009835

**Comment by shawntanzk** [comment]
> I think in the mouse (according to MBA), the magnocellular nucleus is the most ventral part of the ventral region of the palladium (and is disjoint with the substantia innominata).

now mapped this to ventral palladium

**Comment by shawntanzk** [comment]
If all good with the two changes, could you either let me know or change it to verified, after which I will build the bridge :)

**Pull request merged**
