### PR TITLE
Made changes to Makefile

### PR DESCRIPTION
**Pull request by shawntanzk**
- remove reason
- add download sources

Current error: 

```
robot extract --method BOT -i mirror/uberon.owl -T terms.txt remove --axioms disjoint -o uberon_slice.owl
MISSING TERMS ERROR term(s) are required with --term or --term-file
For details see: http://robot.obolibrary.org/errors#missing-terms-error
Use the -vvv option to show the stack trace.
Use the --help option to see usage information.
make: *** [Makefile:71: uberon_slice.owl] Error 1
```

### CODE REVIEW

**Comment by shawntanzk** [comment]
Guessing new UBERON mirror has some changes and something that is being extracted in terms.txt is missing?

**Comment by shawntanzk** [comment]
just looked at terms.txt - don't understand this part:

it is taking all terms for sources_merged which is all the allen files, and extracting terms from it - these are all dhba, mba etc. terms
then we try to use terms.txt to extract from uberon which does not have these terms? 
Did uberon used to merge these files in? Is that why it is is uberon?

**Comment by shawntanzk** [comment]
@dosumis - might need help with this

**Comment by shawntanzk** [comment]
Looking at tmp.owl -> is the aim of uberon_slice to extract out uberon terms in sources_merged.owl? In which case, the sparql query  `terms.sparql` should have a filter to grab only uberon terms?

**Comment by shawntanzk** [comment]
tested the above and came up with the same issue

**Comment by shawntanzk** [comment]
ok we found the problem in that the terms file has <> (eg <http://purl.obolibrary.org/obo/UBERON_0001966>)
robot extract doesn't seem too happy about this, cause when i remove < > from the terms.txt manually it works. 
I currently have a filter to only take out uberon terms but i guess that isn't needed given extract ignores classes that isn't in. Will just add a command to remove the < >, ugur is helping me with it now :) thanks

**Comment by matentzn** [comment]
Consider how ODK does it:

$(PRESEED): $(SRCMERGED)
	$(ROBOT) query -f csv -i $< --query ../sparql/terms.sparql $@.tmp &&\
	cat $@.tmp | sort | uniq >  $@

Using the `-f csv` parameter!

**Comment by shawntanzk** [comment]
perfect, that saves the sed command :) thanks @matentzn

**Comment by shawntanzk** [comment]
next error:

```
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/excel/_openpyxl.py", line 48, in __init__
    from openpyxl.workbook import Workbook
ModuleNotFoundError: No module named 'openpyxl'
make: *** [Makefile:98: report.xlsx] Error 1
```

**Comment by matentzn** [comment]
Yes, if you want to run this inside of ODK (@dosumis did not when he wrote the Makefile), then you need to install that dependency. This is how you _can_ do that:

https://github.com/OBOFoundry/COB/blob/master/src/ontology/cob.Makefile#L86

But it is annoying, I grant you that. I would exclude the report.xlsx from the `make all` probably for now, and then ask David if he stills needs it. If so, add a goal that installs the dependencies like in the example above and run it just before, i.e. 

```
sh run.sh make dependencies all
```

**Comment by shawntanzk** [comment]
report is important, I figured I'll just run on my local machine, but I guess its better to add the dependencies in to the makefile so others can run it

**Comment by shawntanzk** [comment]
yay full run! with a lot of help from a lot of people lol. 
Looks like a lot of diff though, will look through a bit to see if it is just rearrangement or something more that we should look into.

**Pull request merged**
